version: '3.8'

services:

  app:
    build: .
    container_name: backendintern-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/backenddb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:15
    container_name: backendintern-db
    environment:
      POSTGRES_DB: backenddb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: backendintern-redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data: