spring.application.name=BackendIntern

spring.datasource.url=jdbc:postgresql://localhost:5432/assignment_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.operationsSorter=method
springdoc.packages-to-scan=com.assignment.BackendIntern.controller

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
spring.mvc.pathmatch.use-suffix-pattern=false

logging.level.org.springdoc=DEBUG